# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
#
# Mappings Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
#
# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
loader_version_range=[1,)
#
# Mod Properties
mod_version=1.0.0
mod_id=cookielicious
mod_name=Cookielicious
mod_license=All Rights Reserved
mod_group_id=com.cookiejar.cookielicious
#
# Dependency Properties
blueprint_id=7148094
neapolitan_id=7119475
jei_id=7420587
