@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.cookiejar.cookielicious.common.triggers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;