@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.cookiejar.cookielicious.datagen.server;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;