@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cookiejar.cookielicious.datagen.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;