@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.evoslab.cookielicious.datagen.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;